libs =
import libs += libimgui-platform-glfw-docking%lib{imgui-platform-glfw-docking}
import libs += libimgui-render-opengl3-docking%lib{imgui-render-opengl3-docking}

exe{hello}: {hxx ixx txx cxx}{**} $libs testscript

cxx.poptions =+ "-I$out_root" "-I$src_root"
